#!/bin/bash
# 论文提交准备执行脚本
# 执行步骤：格式统一 → 图表生成 → PDF编译 → 投稿

echo "========================================="
echo "  统一场理论论文投稿准备执行计划"
echo "========================================="
echo ""

# 步骤1: 格式统一
echo "[步骤1/4] 格式统一检查"
echo "----------------------------------------"
echo "□ 1.1 统一术语和符号"
echo "   - 检查τ₀, τ_L, τ_T符号一致性"
echo "   - 统一"谱维度" vs "spectral dimension""
echo ""
echo "□ 1.2 图表编号统一"
echo "   - 图1-13连续编号"
echo "   - 检查图表引用"
echo ""
echo "□ 1.3 参考文献格式"
echo "   - 转换为PRD格式"
echo "   - 检查引用完整性"
echo ""

# 步骤2: 图表生成
echo ""
echo "[步骤2/4] 图表生成"
echo "----------------------------------------"
echo "□ 2.1 生成理论框架图 (图1-4)"
echo "   - 使用draw.io或Python"
echo ""
echo "□ 2.2 整合现有图表"
echo "   - JWST_redshift_validation.png → 图12"
echo "   - gw_polarization_validation.png → 图11"
echo "   - cmb_nongaussianity_validation.png → 图10"
echo ""
echo "□ 2.3 生成验证矩阵时间表 (图13)"
echo "   - 使用Python matplotlib"
echo ""

# 步骤3: PDF编译
echo ""
echo "[步骤3/4] PDF编译"
echo "----------------------------------------"
echo "□ 3.1 LaTeX编译"
echo "   - 主文件: paper_main.tex"
echo "   - 参考文献: bibliography.bib"
echo ""
echo "□ 3.2 检查编译错误"
echo "   - 公式编号"
echo "   - 图表引用"
echo "   - 参考文献"
echo ""
echo "□ 3.3 生成最终PDF"
echo "   - paper_final.pdf"
echo ""

# 步骤4: 投稿
echo ""
echo "[步骤4/4] 投稿准备"
echo "----------------------------------------"
echo "□ 4.1 准备投稿材料"
echo "   - 投稿信 (cover_letter.pdf)"
echo "   - 作者声明 (author_statement.pdf)"
echo "   - 利益冲突声明 (conflict_of_interest.pdf)"
echo ""
echo "□ 4.2 在线投稿"
echo "   - 期刊: Physical Review D"
echo "   - 网址: https://journals.aps.org/prd/submit/"
echo ""
echo "□ 4.3 提交确认"
echo "   - 保存投稿编号"
echo "   - 设置审稿提醒"
echo ""

echo "========================================="
echo "  预计总时间: 2-3天"
echo "========================================="
